#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : dj-database-url
Version  : 0.5.0
Release  : 4
URL      : https://files.pythonhosted.org/packages/01/c4/98fbf678e810029be8078419f7bba626aafa2e81bc38748757db954c477c/dj-database-url-0.5.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/01/c4/98fbf678e810029be8078419f7bba626aafa2e81bc38748757db954c477c/dj-database-url-0.5.0.tar.gz
Summary  : Use Database URLs in your Django Application.
Group    : Development/Tools
License  : BSD-2-Clause
Requires: dj-database-url-license = %{version}-%{release}
Requires: dj-database-url-python = %{version}-%{release}
Requires: dj-database-url-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
DJ-Database-URL
~~~~~~~~~~~~~~~
.. image:: https://secure.travis-ci.org/kennethreitz/dj-database-url.svg?branch=master
:target: http://travis-ci.org/kennethreitz/dj-database-url

%package license
Summary: license components for the dj-database-url package.
Group: Default

%description license
license components for the dj-database-url package.


%package python
Summary: python components for the dj-database-url package.
Group: Default
Requires: dj-database-url-python3 = %{version}-%{release}

%description python
python components for the dj-database-url package.


%package python3
Summary: python3 components for the dj-database-url package.
Group: Default
Requires: python3-core

%description python3
python3 components for the dj-database-url package.


%prep
%setup -q -n dj-database-url-0.5.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1551027945
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dj-database-url
cp LICENSE %{buildroot}/usr/share/package-licenses/dj-database-url/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dj-database-url/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
